fat/Areas/Admin/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FAT.DataAccess.Data.Repository;
using FAT.Models;
using Microsoft.AspNetCore.Mvc;

namespace FAT.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServicesController : Controller
    {
        private readonly IContainer _container;

        public ServicesController(IContainer container)
        {
            _container = container;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Services service)
        {
            if (ModelState.IsValid)
            {
                _container.Service.Add(service);
                _container.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Services services = new Services();
            services = _container.Service.Get(id);
            if (services == null)
            {
                return NotFound();
            }

            return View(services);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Services service)
        {
            if (ModelState.IsValid)
            {
                _container.Service.Update(service);
                _container.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        

        #region call api
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new {data = _container.Service.GetAll()});
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _container.Service.Get(id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Error al borrar el servicio" });
            }

            _container.Service.Remove(objFromDb);
            _container.Save();
            return Json(new { success = true, message = "Servicio Borrado" });
        }

        #endregion
    }
}

fat/Areas/Admin/Controllers/TurnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FAT.Areas.User.Controllers;
using FAT.DataAccess.Data;
using FAT.DataAccess.Data.Repository;
using FAT.Models;
using FAT.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FAT.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TurnController : Controller
    {
        private readonly IContainer _container;
        private readonly ApplicationDbContext _context;

        public TurnController(IContainer container, ApplicationDbContext context)
        {
            _container = container;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create(int idService, string tittleService)
        {
            var queue_assign = 0;
            TempData["idService"] = idService;
            TempData["tittleService"] = tittleService;
            var queue_count_1 = _context.Turn.Where(q => q.QueueId == 1 && q.Status == 0).Count();
            var queue_count_2 = _context.Turn.Where(q => q.QueueId == 2 && q.Status == 0).Count();
            var time_queue_1 = _context.Queue.Where(t => t.id == 1).FirstOrDefault();
            var time_queue_2 = _context.Queue.Where(t => t.id == 2).FirstOrDefault();

            if (queue_count_1 * time_queue_1.time <= queue_count_2 * time_queue_2.time)
            {
                queue_assign = 1;
            }
            else
            {
                queue_assign = 2;
            }
            TempData["queueAssign"] = queue_assign.ToString();

            return View();
        }

        [HttpGet]
        public IActionResult GetTurns()
        {
            var getTurns = from turn in _context.Turn
                           join dataturn in _context.DataTurn
                           on turn.Id equals dataturn.id_turn
                           join serv in _context.Services
                           on turn.ServicesId equals serv.id
                           join queu in _context.Queue
                           on turn.QueueId equals queu.id
                           select new
                           {
                               cliid = turn.Cliid,
                               cliente = turn.CliName,
                               status = turn.Status,
                               posicion = dataturn.position,
                               tiempo_espera = dataturn.process_time,
                               tipo_servicio = serv.header,
                               cola = queu.name_queue

                           };


            JArray jArray = JArray.FromObject(getTurns.ToList());
            @TempData["ListTurn"] = JsonConvert.SerializeObject(getTurns.ToList());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Turn turn)
        {
            if (ModelState.IsValid)
            {
                _container.Turn.Add(turn);
                _container.Save();

                var time = _context.Queue.Where(t => t.id == turn.QueueId).FirstOrDefault();
                var pending_shifts = _context.Turn.Where(p => p.Status == 0 && p.QueueId == turn.QueueId).Count();

                DateTime now = DateTime.Now;
                DataTurn dataTurn = new DataTurn();
                dataTurn.id_turn = turn.Id;
                dataTurn.id_queue = turn.QueueId;
                dataTurn.position = pending_shifts + 1;
                dataTurn.process_time = now.AddMinutes(pending_shifts * time.time);
                _context.DataTurn.Add(dataTurn);
                _context.SaveChanges();


                return Redirect("/");
            }
            return View(turn);
        }

        
            #region call api
            [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new
            {
                data = from turn in _context.Turn
                       join data in _context.DataTurn
                       on turn.Id equals data.id_turn
                       where turn.Status == 0
                       select new
                       {
                           id = turn.Id,
                           time = data.process_time,
                           status = turn.Status
                       }
            });
        }

        


        [HttpPut]
        public IActionResult Put(Turn turn, int id)
        {
            
            turn.Status = 1;
            turn.Id = id;
            _container.Turn.Update(turn);
            _container.Save();

            return Json(new { success = true, message = "Actualizando status turno: " + id + " fue atendido"});
        }
        #endregion

    }

}

fat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FAT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui-1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <img class="logo-fat" />
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="User" asp-controller="Home" asp-action="Index">Inicio</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Administración</a>
                        <div class="dropdown-menu">
                            @if (User.IsInRole(FAT.CNT.CNT.Admin))
                            {
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Services" asp-action="Index">Tipo de servicio</a>
                            }
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Turn" asp-action="GetTurns">Listado de turnos</a>
                        </div>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p>Copyright FAT S.A &copy; @DateTime.Now.Year</p>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!--Additional libraries-->
    <script src="~/lib/jquery-ui-1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.1.0/jquery.serializejson.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/0f48d8c00d.js" crossorigin="anonymous"></script>
    <!--END Additional libraries-->
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

fat/Views/Shared/_ViewCreateBack.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Crear</button>
        &nbsp;
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Volver a listado</a>
    </div>
</div>